name: dijning
favicon: null
layout_spectrum: 0.60522
typography_spectrum: 0.3797662379220128
title: 'DIJNING - on how technology affects the way we create, distribute and listen to music '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#967e72'
    - '#bbb7ae'
    - '#ffffff'
    - '#13132b'
    - '#414050'
  brandStrength: 0.5415664101019502
  lightness: 0.25
  saturation: 0.3125
  rhythmicContrast: 0.3861954731401056
purpose: []
